
name: Get Bitwarden To Aliyun

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:
  

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-chengdu
  REGISTRY: registry.cn-chengdu.aliyuncs.com
  NAMESPACE: tickg
  IMAGE: bitwarden-self-host
  #TAG: beta
  TAG: dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:

    - name: show env
      run: |
        pwd
        uname -a
        whoami
        
    
    # 1.1 Login to ACR
    - name: Login to ACR with the AccessKey pair
      uses: aliyun/acr-login@v1
      with:
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"

    # 1.2 Build and push image to ACR
    - name: Build and push image to ACR
      run: |
        docker pull bitwarden/self-host:$TAG
        docker images
        docker tag bitwarden/self-host:$TAG "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"
        docker images
        docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"
        

