
name: Get Bitwarden To Aliyun

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 同步的版本tag
        # Default value if no value is explicitly provided
        default: 'beta'
        # Input has to be provided for the workflow to run
        required: true  

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-chengdu
  REGISTRY: registry.cn-chengdu.aliyuncs.com
  NAMESPACE: tickg
  IMAGE: bitwarden-self-host
  #TAG: beta
  TAG: "${{ github.event.inputs.tag }}"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: push_to_aliyun

    steps:

    - name: Show Env
      run: |
        echo curdir=$(pwd)
        echo sysinfo=$(uname -a)
        echo whoami=$(whoami)
        
    # 1 Login to ACR
    - name: Login to ACR with the AccessKey pair
      uses: aliyun/acr-login@v1.0.6
      with:
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        #login-server: "${{ env.REGISTRY }}"
        #username: "${{ secrets.USERNAME }}"
        #password: "${{ secrets.PASSWORD }}"

    # 2 Scan image in ACR
    - name: Scan image in ACR
      uses: aliyun/acr-scan@v1.0.4
      with:
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        repository: "${{ env.NAMESPACE }}/${{ env.IMAGE }}"
        tag: "${{ env.TAG }}"
        
    # 3 Build and push image to ACR
    - name: Build and push image to ACR
      env: 
        ACR_USER: ${{ secrets.USERNAME }}
        ACR_PASS: ${{ secrets.PASSWORD }} 
      run: |
        exit 0
        #docker login -u "$USERNAME" -p "$PASSWORD"  "$REGISTRY"
        docker pull bitwarden/self-host:$TAG
        docker images
        docker tag bitwarden/self-host:$TAG "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"
        docker images
        docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"
        

